name: voice_notes
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  record: ^5.2.0
  permission_handler: ^11.3.1
  path_provider: ^2.1.5

  just_audio: ^0.9.43

  flutter_bloc: ^8.1.6
  equatable: ^2.0.7

  flutter_feather_icons: ^2.0.0
  intl: ^0.20.1
  flutter_svg: ^2.0.17
  infinite_scroll_pagination: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/dubai/
    - assets/images/

  fonts:
    - family: dubai
      fonts:
        - asset: assets/fonts/dubai/Dubai-Regular.ttf
          weight: 400
        - asset: assets/fonts/dubai/Dubai-Medium.ttf
          weight: 500
        - asset: assets/fonts/dubai/Dubai-Bold.otf
          weight: 700